version: '2'

services:
  postgres:
    image: postgres:9.4

  pgbouncer:
    image: pgbouncer/pgbouncer:latest
    environment: 
      - DATABASES_HOST=postgres
    links:
      - postgres
    ports:
      - "6432:6432"
